spring:
  #添加静态资源
  #开发环境
  profiles:
    active: dev
  #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**  #排除文件(不重启项目)
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  datasource:
#    url: jdbc:mysql://localhost:3306/javaspringboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.48.48.165:3306/javaspringboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456


  redis:
#    host: 127.0.0.1   # 本地上面的redis
    host: 120.48.48.165  # 自己服务器上面的redis
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 200
        max-idle: 20
        min-idle: 2
    timeout: 20000

server:
  port: 9001

mybatis:
  type-aliases-package: com.example.demo.mapper
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:/mappers/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  # type-aliases-package: com.example/demo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

# 日志配置
logging:
  level:
    root: info
    # web日志
    org.springframework.web: debug
    # security 日志
    org.springframework.security: warn
    # mybatis日志
    org.mybatis: debug
  charset:
    # 输出控制台编码
    console: UTF-8
    # 输出文件编码
    file: UTF-8
  # 输出文件名及路径，不配置则不输出文件
  file:
    # 切记，该文件表示正在产出日志的日志文件。并不会打包，当文件大于max-file-size,会根据file-name-pattern格式打包
    # 名称为log/ota.log文件夹会在项目根目录下，打包后会在启动包同目录下；名称为/log/ota.log的文件夹会在项目所在磁盘的跟目录下
    name: log/SpringBootJavaWeb.log
  logback:
    rollingpolicy:
      # 单文件的大小，默认10M, 超过之后打包成一个日志文件
      max-file-size: 10MB
      # 日志保存的天数
      max-history: 10
      # 打包文件格式,默认： ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz,书写格式为：文件路径/文件名.%i.文件后缀,其中%i不可省去，否则无日志显示
      # 例如： 日期为：2021/11/5 ,则打包文件之后为： log/ota.2021-11-05.0.gz,0表示日志的第一部分，后续就是，1,2,3...
      # 如果是压缩包，里面会多一个名log/ota.2021-11-05.0的日志文件
      # 如下面的例子，打包之后为: log/2021-11/ota.2020-11-5.0.log，这是一个日志文件
      file-name-pattern: log/%d{yyyy-MM}/ota.%d{yyyy-MM-dd}.%i.log
